name: versionarte
description: Manage your Flutter app's versioning and availability remotely.
version: 0.9.1
repository: https://github.com/kamranbekirovyz/versionarte
home: https://github.com/kamranbekirovyz/versionarte
issue_tracker: https://github.com/kamranbekirovyz/versionarte/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_remote_config: ^4.3.8
  http: ^1.1.2
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.1
  pub_semver: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0